### ISSUE TITLE
A minor suggestion about import print out

### ISSUE THREAD

**Issue by jianlins** [Blulab-Utah/domainOntology#11]
Currently no matter where ModifierOntology and SchemaOntology are imported, the consol will always print 
Loaded imports: 
http://blulab.chpc.utah.edu/ontologies/ModifierOntology.owl
http://blulab.chpc.utah.edu/ontologies/SchemaOntology.owl
This isn't informative to the user. 
Suggest adding "... from the file: <file name>" at the end.

**Comment by mecst76** [comment]
It's there just for me. I needed to make sure the imports were loaded properly. I don't really care where they come from, just that they appear. :) The system out will probably be removed at some point once I know the code has stabilized.

**Comment by jianlins** [comment]
It is useful for me as well, especially when multiple version of ontology files exist. I would suggest keep it.
