### ISSUE TITLE
Can you create a test case for demo the api?

### ISSUE THREAD

**Issue by jianlins** [Blulab-Utah/domainOntology#6]
Add a boolean parameter in previous test code, doesn't work. domainVariables size is 0.

> DomainOntology domain = new DomainOntology("src/main/resourc/colonoscopy_20141001.owl",true);
> ArrayList<Variable> domainVariables = domain.getAllVariables();

I tried the owl files in resource_ontologies project (I assume they are new ones for the new API), still not work. 

Thanks

**Comment by mecst76** [comment]
First, you cannot use that ontology. It was not built by me and it uses the old versions of the ontology. Second, if you pass the boolean true that means you must have the domain ontology and all of the imported ontologies (Schema, ConText and TermMapping) stored locally in the same directory as the domain ontology. I'll send you info shortly on how to get information from the domain ontology.
